export const UPDATE_LANDSCAPE = 'UPDATE_LANDSCAPE';
export const UPDATE_INPUTING = 'UPDATE_INPUTING';
export const UPDATE_DIRECTION = 'UPDATE_DIRECTION';
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS';

//加载数据中
export const FETCHING = 'FETCHING';
export const CART_FETCHING = 'CART_FETCHING';
export const ADDRESS_FETCHING = 'ADDRESS_FETCHING';
export const CATALOG_FETCHING = 'CATALOG_FETCHING';
export const CLEAR = 'CLEAR';

export const SEARCH = 'SEARCH';
//查询结束
export const SEARCH_END = 'SEARCH_END';
//下拉状态
export const SCROLL_TOP_STATUS = 'SCROLL_TOP_STATUS';
//上拉状态
export const SCROLL_BOTTOM_STATUS = 'SCROLL_BOTTOM_STATUS';

export const KEYWORD_CHANGE = 'KEYWORD_CHANGE';

export const ADD_TO_CART = 'ADD_TO_CART';

export const LOGIN = 'LOGIN';


export const UPDATE_CART_TOTAL = 'UPDATE_CART_TOTAL';
export const UPDATE_CART_NUMBER = 'UPDATE_CART_NUMBER';
export const UPDATE_CART_ALL_CHECKED = 'UPDATE_CART_ALL_CHECKED';
export const UPDATE_CART_GOODS = 'UPDATE_CART_GOODS';


export const UPDATE_ADDRESS_LIST = 'UPDATE_ADDRESS_LIST';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_FAIL = 'UPDATE_ADDRESS_FAIL';
